### ISSUE TITLE
New design for wallpaper

### ISSUE THREAD

**Issue by mcder3** [manjaro/artwork-breath#1]
I open this topic in github to know the devs point of view on the new wallpaper

[Imagen](https://forum.manjaro.org/t/breath-before-maia-2-for-2017-plasma-5/13118/75?u=mcder3)

I know it's a last minute change, but I think it looks more elegant and nice with a more colorful touch.

**Comment by Kirek** [comment]
I like them

**Comment by Huluti** [comment]
For me it's perfect. It is not because the main color of Manjaro is green that it should be used everywhere. I prefer to have touches of green in some well chosen places and have a visual appearance successful. This wallpaper adds more color and is for me more attractive.

**Comment by mcder3** [comment]
In my opinion, we do not need to paint everything in green to say that it is Manjaro.

And I'm thinking of changing the position of the colors.

http://imgur.com/ymglLFt

http://imgur.com/FqNsbQ3
