### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by ayanb1991** [manjaro/artwork-breath#14]
Can you please provide installation instructions, I am using KDE Neon, Thanks in advance.

**Comment by lisamccoy** [comment]
You can check within our [PKGBUILD](https://github.com/manjaro/packages-community/blob/master/artwork-breath/PKGBUILD). However installation can be done also the classic way:

```
mkdir -p build
cd build
cmake ../breath \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
make
make install
```

**Comment by ayanb1991** [comment]
Thanks for the reply, Followed the instructions. Desktop themes are applied. But neither "Icons" or "Window Decoration" is installed. Please help.

**Comment by lisamccoy** [comment]
Are you sure. Check the console output what got installed and where. Icons you find normally in `/usr/share/icons` else should be in `/usr/share/plasma`. If that differs in KDE Neon, then you might need to change the install prefix.

**Comment by murilolobato** [comment]
I'm using Antergos with Plasma 5, can I use this theme? How to install?

**Comment by oberon2007** [comment]
This has been answered by @philmmanjaro already a few comments up. Just use the PKGBUILD to install, that's how we do it on Manjaro aswell 😉
