### ISSUE TITLE
Disabled text issue

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/artwork-breath#4]
Text of disabled items is not showed correctly. There is not   almost any difference betweeen texts of active and disabled items!!
Screenshot from MonoDevelop:
![screenshot_20170320_135824](https://cloud.githubusercontent.com/assets/5506156/24095300/e808b80e-0d75-11e7-8d32-90a95e414656.png)

Thanks for your great work,
I am using latest Manjaro Kde Stable Edition.

**Comment by mcder3** [comment]
Is the "MonoDevelop" application made for GTK or QT5?

**Comment by ceyhunnabiyev** [comment]
GTK application; 
Issue on breath-gtk-theme I think, because when I select arc-gtk-theme from Gnome Application Style,  no issue occurred. I love your theme and of course manjaro. Can you fix this ??

**Comment by mcder3** [comment]
In this case I can not help you, since I only work on the artwork of Plasma 5 (QT)

You can help in this case please @Kirek

**Comment by ceyhunnabiyev** [comment]
Where do I create new issue according to breath-gtk-theme, @mcder3,  @Kirek? I love breath theme
