### ISSUE TITLE
breath dark unreadable text and too dark link color 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [manjaro/artwork-breath#5]
Breath dark theme  looks really fantastic, but there are small issues on it. I took screenshots:

![screenshot_20170321_181308](https://cloud.githubusercontent.com/assets/5506156/24152442/15b3fb7a-0e65-11e7-98d8-63daa71a90ec.png)

![screenshot_20170321_183437](https://cloud.githubusercontent.com/assets/5506156/24152449/1cb33bd4-0e65-11e7-9eec-b5ef2d6fc0fa.png)

I am using latest Manjaro Kde Stable Release,
All my selected styles are breath dark, including gnome application style and color scheme

**Comment by mcder3** [comment]
I can not help in the applications made in GTK, you have open the VLC when you changed color?

**Comment by ceyhunnabiyev** [comment]
Vlc is OK on theme, @mcder3,  but  some windows of VLC still use light variant, for example, "about" window (screenshot is above). I think, this  is  happened in other applications

**Comment by mcder3** [comment]
I will review that problem over the course of the day to see that you are experiencing this problem.

**Comment by ceyhunnabiyev** [comment]
Thanks, Great Work!!!

**Comment by mcder3** [comment]
Apparently it is a plasma 5 error

![bug](https://cloud.githubusercontent.com/assets/1154298/24331762/03eb94e8-11f8-11e7-8936-c838143181d7.png)

Since the error is replicated with the dark color schemes

**Comment by ceyhunnabiyev** [comment]
@mcder3, if you can't do anything, take it easy. it is not important for me, just I wanted to help you. My important issue is according to breath-gtk-theme, because I am working on MonoDevelop, breath-gtk-theme looks greater on MonoDevelop even than arc-gtk-theme. Please help me where I put issue related to  breath-gtk-theme?
