### ISSUE TITLE
SDDM missing wallpaper

### ISSUE THREAD

**Issue by pmargeti34** [manjaro/artwork-breath#9]
sddm-breath-theme 0.2.1-1 seems to be missing default wallpaper, it shows a gray background instead.

**Comment by philmmanjaro** [comment]
The needed wallpaper is included in the package. Did you reload the theme?

**Comment by Kirek** [comment]
It seems the .conf file changed a little, so it doesn't set the previous configured background. I will make a workaround later today.

**Comment by pmargeti34** [comment]
Can confirm update fixes the issue. Thanks!
